### ISSUE TITLE
The "how to type out emoji" section needs a note about the Windows 10 emoji palette

### ISSUE THREAD

**Issue by kotauskas** [cooperka/emoji-commit-messages#4]
So far, the [How to type emoji on your computer] section only mentions a wacky Windows 8 solution to the problem. On Windows 10, pressing `Win`+`.` opens up an emoji palette which supports searching for emojis. Perhaps it's worth mentioning as the new preferred solution.

[How to type emoji on your computer]: https://github.com/cooperka/emoji-commit-messages#how-to-type-emoji-on-your-computer " "

**Comment by cooperka** [comment]
Wonderful news! Do you mind submitting a PR to update the readme?

**Comment by kotauskas** [comment]
> Wonderful news! Do you mind submitting a PR to update the readme?

Just submitted #5 which implements those changes.
