### ISSUE TITLE
Added 2 new ones and changed meaning of 2 emojis in my fork

### ISSUE THREAD

**Issue by mationai** [cooperka/emoji-commit-messages#7]
Changes are in stated in a new column. Let me know if you like them, and I'll submit a PR. If not, I'll close this.

https://github.com/fuzzthink/emoji-commit-messages

**Comment by cooperka** [comment]
These changes look great @fuzzthink -- I support you using them yourself but I personally prefer my own 🤷 Thanks for offering to submit a PR.
